# Generated by Django 4.2.2 on 2023-06-22 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("session", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="chassis",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="session.chassis",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="engine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="session.engine",
            ),
        ),
    ]
