# Generated by Django 4.2.2 on 2023-06-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session", "0002_session_chassis_session_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="temp",
            field=models.IntegerField(
                blank=True,
                help_text="Please enter the temperature in Fahrenheit.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="track_conditions",
            field=models.TextField(
                blank=True,
                help_text="Please enter a brief description of thetrack conditions.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="weather",
            field=models.CharField(
                default="sunny",
                help_text="Sunny, cloudy, rainy, pouring, etc.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="rim",
            field=models.CharField(help_text="Enter a rim type.", max_length=200),
        ),
    ]
