# Generated by Django 4.2.7 on 2023-11-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_rename_gear_session_sprocket_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('SODI', 'SODI Kart'), ('BirelArt', 'BirelArt'), ('Tony Kart', 'Tony Kart'), ('Red Speed', 'Red Speed'), ('CompKart', 'CompKart'), ('KartRepublic', 'Kart Republic'), ('Kosmic', 'Kosmic')], max_length=200),
        ),
    ]
