# Generated by Django 4.2.7 on 2023-11-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_session_time_alter_chassis_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='high_jetting',
            field=models.IntegerField(blank=True, default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='low_jetting',
            field=models.IntegerField(blank=True, default=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('Tony Kart', 'Tony Kart'), ('Kosmic', 'Kosmic'), ('Red Speed', 'Red Speed'), ('CompKart', 'CompKart'), ('SODI', 'SODI Kart'), ('BirelArt', 'BirelArt'), ('KartRepublic', 'Kart Republic')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='jet_size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(),
        ),
    ]
