# Generated by Django 4.2.7 on 2023-11-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_session_high_jetting_session_low_jetting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='jet_size',
        ),
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('Red Speed', 'Red Speed'), ('Tony Kart', 'Tony Kart'), ('SODI', 'SODI Kart'), ('CompKart', 'CompKart'), ('BirelArt', 'BirelArt'), ('Kosmic', 'Kosmic'), ('KartRepublic', 'Kart Republic')], max_length=200),
        ),
    ]
