# Generated by Django 4.2.7 on 2024-01-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_alter_chassis_brand_alter_session_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('SODI', 'SODI Kart'), ('KartRepublic', 'Kart Republic'), ('BirelArt', 'BirelArt'), ('CompKart', 'CompKart'), ('Kosmic', 'Kosmic'), ('Tony Kart', 'Tony Kart'), ('Red Speed', 'Red Speed')], max_length=200),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='year',
            field=models.IntegerField(blank=True, choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024, help_text='Enter the year the chassis model came out.', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('USPKS', 'US Pro Karting Series'), ('NEKC', 'Northeast Karting Championship'), ('Rotax', 'Rotax Races'), ('SKUSA', 'Super Karts USA'), ('WSK', 'World Series Karting'), ('Italian Championship', 'Italian Championship'), ('RokCup', 'ROK Cup'), ('Stars', 'Stars')], max_length=100),
        ),
    ]
