# Generated by Django 4.2.7 on 2024-01-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0010_alter_chassis_brand_alter_chassis_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('SODI', 'SODI Kart'), ('CompKart', 'CompKart'), ('Tony Kart', 'Tony Kart'), ('BirelArt', 'BirelArt'), ('KartRepublic', 'Kart Republic'), ('Red Speed', 'Red Speed'), ('Kosmic', 'Kosmic')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('Stars', 'Stars'), ('NEKC', 'Northeast Karting Championship'), ('WSK', 'World Series Karting'), ('SKUSA', 'Super Karts USA'), ('USPKS', 'US Pro Karting Series'), ('RokCup', 'ROK Cup'), ('Rotax', 'Rotax Races'), ('Italian Championship', 'Italian Championship')], max_length=100),
        ),
    ]
