# Generated by Django 4.2.7 on 2024-01-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0011_alter_chassis_brand_alter_session_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='egt_max1',
            field=models.IntegerField(blank=True, help_text='Max EGT of the best lap', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='egt_max2',
            field=models.IntegerField(blank=True, help_text='Max EGT of the second best lap', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='egt_max3',
            field=models.IntegerField(blank=True, help_text='Max EGT of the third best lap', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='egt_min1',
            field=models.IntegerField(blank=True, help_text='min EGT of the best lap', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='egt_min2',
            field=models.IntegerField(blank=True, help_text='min EGT of the second best lap', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='egt_min3',
            field=models.IntegerField(blank=True, help_text='min EGT of the third best lap', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='lap_time1',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The best lap time', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='lap_time2',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The second best lap time', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='lap_time3',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The third best lap time', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='rpm_max1',
            field=models.IntegerField(blank=True, help_text='Max RPM of the best lap', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='rpm_max2',
            field=models.IntegerField(blank=True, help_text='Max RPM of the second best lap', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='rpm_max3',
            field=models.IntegerField(blank=True, help_text='Max RPM of the third best lap', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='rpm_min1',
            field=models.IntegerField(blank=True, help_text='min RPM of the best lap', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='rpm_min2',
            field=models.IntegerField(blank=True, help_text='min RPM of the second best lap', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='rpm_min3',
            field=models.IntegerField(blank=True, help_text='min RPM of the third best lap', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='speed_max1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The max speed of the best lap', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='speed_max2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The max speed of the second best lap', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='speed_max3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The max speed of the third best lap', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='speed_min1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The min speed of the best lap', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='speed_min2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The min speed of the second best lap', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='speed_min3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The min speed of the third best lap', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('BirelArt', 'BirelArt'), ('Red Speed', 'Red Speed'), ('SODI', 'SODI Kart'), ('Kosmic', 'Kosmic'), ('Tony Kart', 'Tony Kart'), ('CompKart', 'CompKart'), ('KartRepublic', 'Kart Republic')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('RokCup', 'ROK Cup'), ('NEKC', 'Northeast Karting Championship'), ('WSK', 'World Series Karting'), ('Rotax', 'Rotax Races'), ('USPKS', 'US Pro Karting Series'), ('SKUSA', 'Super Karts USA'), ('Stars', 'Stars'), ('Italian Championship', 'Italian Championship')], max_length=100),
        ),
    ]
