# Generated by Django 4.2.7 on 2024-01-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_session_egt_max1_session_egt_max2_session_egt_max3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('KartRepublic', 'Kart Republic'), ('SODI', 'SODI Kart'), ('Tony Kart', 'Tony Kart'), ('CompKart', 'CompKart'), ('BirelArt', 'BirelArt'), ('Red Speed', 'Red Speed'), ('Kosmic', 'Kosmic')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('WSK', 'World Series Karting'), ('Italian Championship', 'Italian Championship'), ('SKUSA', 'Super Karts USA'), ('Rotax', 'Rotax Races'), ('RokCup', 'ROK Cup'), ('USPKS', 'US Pro Karting Series'), ('NEKC', 'Northeast Karting Championship'), ('Stars', 'Stars')], max_length=100),
        ),
    ]
