# Generated by Django 4.2.7 on 2024-01-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0013_alter_chassis_brand_alter_session_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('BirelArt', 'BirelArt'), ('Red Speed', 'Red Speed'), ('Kosmic', 'Kosmic'), ('Tony Kart', 'Tony Kart'), ('CompKart', 'CompKart'), ('KartRepublic', 'Kart Republic'), ('SODI', 'SODI Kart')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='high_jetting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='low_jetting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('Rotax', 'Rotax Races'), ('NEKC', 'Northeast Karting Championship'), ('USPKS', 'US Pro Karting Series'), ('Italian Championship', 'Italian Championship'), ('Stars', 'Stars'), ('SKUSA', 'Super Karts USA'), ('RokCup', 'ROK Cup'), ('WSK', 'World Series Karting')], max_length=100),
        ),
    ]
