# Generated by Django 4.2.7 on 2024-01-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0014_alter_chassis_brand_alter_session_high_jetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('BirelArt', 'BirelArt'), ('Red Speed', 'Red Speed'), ('KartRepublic', 'Kart Republic'), ('CompKart', 'CompKart'), ('Kosmic', 'Kosmic'), ('SODI', 'SODI Kart'), ('Tony Kart', 'Tony Kart')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('USPKS', 'US Pro Karting Series'), ('Italian Championship', 'Italian Championship'), ('WSK', 'World Series Karting'), ('Rotax', 'Rotax Races'), ('RokCup', 'ROK Cup'), ('SKUSA', 'Super Karts USA'), ('Stars', 'Stars'), ('NEKC', 'Northeast Karting Championship')], max_length=100),
        ),
    ]
