# Generated by Django 4.2.7 on 2024-01-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0015_alter_chassis_brand_alter_session_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('PF', 'Pre-final race'), ('F', 'Final race'), ('H', 'Heat race'), ('P', 'General Practice'), ('Q', 'Qualifying Practice')], default='P', max_length=3),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('Kosmic', 'Kosmic'), ('Red Speed', 'Red Speed'), ('KartRepublic', 'Kart Republic'), ('CompKart', 'CompKart'), ('BirelArt', 'BirelArt'), ('Tony Kart', 'Tony Kart'), ('SODI', 'SODI Kart')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('RokCup', 'ROK Cup'), ('Stars', 'Stars'), ('Rotax', 'Rotax Races'), ('SKUSA', 'Super Karts USA'), ('WSK', 'World Series Karting'), ('NEKC', 'Northeast Karting Championship'), ('USPKS', 'US Pro Karting Series'), ('Italian Championship', 'Italian Championship')], max_length=100),
        ),
    ]
