# Generated by Django 4.2.7 on 2024-01-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0016_session_session_type_alter_chassis_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('BirelArt', 'BirelArt'), ('Red Speed', 'Red Speed'), ('Tony Kart', 'Tony Kart'), ('SODI', 'SODI Kart'), ('Kosmic', 'Kosmic'), ('CompKart', 'CompKart'), ('KartRepublic', 'Kart Republic')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('SKUSA', 'Super Karts USA'), ('Italian Championship', 'Italian Championship'), ('WSK', 'World Series Karting'), ('Stars', 'Stars'), ('USPKS', 'US Pro Karting Series'), ('RokCup', 'ROK Cup'), ('NEKC', 'Northeast Karting Championship'), ('Rotax', 'Rotax Races')], max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Qualifying', 'Qualifying Practice'), ('Practice', 'General Practice'), ('Final', 'Final race'), ('Pre-final', 'Pre-final race'), ('Heat', 'Heat race')], default='Practice', max_length=20),
        ),
    ]
