# Generated by Django 4.2.7 on 2024-01-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0017_alter_chassis_brand_alter_session_race_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='tire_pressure',
        ),
        migrations.AddField(
            model_name='session',
            name='tire_pressure_fl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pressure of the front left tire', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tire_pressure_fr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pressure of the front right tire', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tire_pressure_rl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pressure of the rear left tire', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tire_pressure_rr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pressure of the rear right tire', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('Tony Kart', 'Tony Kart'), ('BirelArt', 'BirelArt'), ('Kosmic', 'Kosmic'), ('KartRepublic', 'Kart Republic'), ('CompKart', 'CompKart'), ('Red Speed', 'Red Speed'), ('SODI', 'SODI Kart')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='low_jetting',
            field=models.IntegerField(blank=True, help_text='Low jetting for Tillotson carb (in minutes) or main jet size for Dellorto carb', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('Stars', 'Stars'), ('NEKC', 'Northeast Karting Championship'), ('Italian Championship', 'Italian Championship'), ('RokCup', 'ROK Cup'), ('Rotax', 'Rotax Races'), ('USPKS', 'US Pro Karting Series'), ('SKUSA', 'Super Karts USA'), ('WSK', 'World Series Karting')], max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Final', 'Final race'), ('Pre-final', 'Pre-final race'), ('Heat', 'Heat race'), ('Practice', 'General Practice'), ('Qualifying', 'Qualifying Practice')], default='Practice', max_length=20),
        ),
    ]
