# Generated by Django 4.2.7 on 2024-01-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0018_remove_session_tire_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('SODI', 'SODI Kart'), ('CompKart', 'CompKart'), ('KartRepublic', 'Kart Republic'), ('Tony Kart', 'Tony Kart'), ('Kosmic', 'Kosmic'), ('BirelArt', 'BirelArt'), ('Red Speed', 'Red Speed')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('USPKS', 'US Pro Karting Series'), ('WSK', 'World Series Karting'), ('Rotax', 'Rotax Races'), ('RokCup', 'ROK Cup'), ('SKUSA', 'Super Karts USA'), ('Stars', 'Stars'), ('NEKC', 'Northeast Karting Championship'), ('Italian Championship', 'Italian Championship')], max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Heat', 'Heat race'), ('Qualifying', 'Qualifying Practice'), ('Final', 'Final race'), ('Practice', 'General Practice'), ('Pre-final', 'Pre-final race')], default='Practice', max_length=20),
        ),
    ]
