# Generated by Django 4.2.7 on 2024-01-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0020_remove_session_carburetor_session_rear_axle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='carburetor',
            field=models.CharField(blank=True, help_text='Type of carb.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('Kosmic', 'Kosmic'), ('KartRepublic', 'Kart Republic'), ('CompKart', 'CompKart'), ('SODI', 'SODI Kart'), ('Red Speed', 'Red Speed'), ('BirelArt', 'BirelArt'), ('Tony Kart', 'Tony Kart')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('NEKC', 'Northeast Karting Championship'), ('WSK', 'World Series Karting'), ('USPKS', 'US Pro Karting Series'), ('RokCup', 'ROK Cup'), ('Stars', 'Stars'), ('SKUSA', 'Super Karts USA'), ('Italian Championship', 'Italian Championship'), ('Rotax', 'Rotax Races')], max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Practice', 'General Practice'), ('Final', 'Final race'), ('Heat', 'Heat race'), ('Qualifying', 'Qualifying Practice'), ('Pre-final', 'Pre-final race')], default='Practice', max_length=20),
        ),
    ]
