# Generated by Django 4.2.7 on 2024-01-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0022_alter_chassis_brand_alter_session_race_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_general_notes',
            field=models.TextField(blank=True, help_text='Driver spun, stopped/started raining, should have used bigger sprocket, etc.', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='sprocket_range',
            field=models.CharField(blank=True, help_text='Please enter a sprocket range if running a shifter kart.Leave blank otherwise'),
        ),
        migrations.AddField(
            model_name='session',
            name='tire_type',
            field=models.CharField(blank=True, default='slick', help_text='Wets or slick?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('CompKart', 'CompKart'), ('SODI', 'SODI Kart'), ('Red Speed', 'Red Speed'), ('Tony Kart', 'Tony Kart'), ('KartRepublic', 'Kart Republic'), ('Kosmic', 'Kosmic'), ('BirelArt', 'BirelArt')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='lap_time1',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The best lap time, in seconds', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='lap_time2',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The second best lap tim, in seconds', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='lap_time3',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The third best lap time, in seconds', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('SKUSA', 'Super Karts USA'), ('None', 'None'), ('Rotax', 'Rotax Races'), ('Italian Championship', 'Italian Championship'), ('Stars', 'Stars'), ('RokCup', 'ROK Cup'), ('NEKC', 'Northeast Karting Championship'), ('WSK', 'World Series Karting'), ('USPKS', 'US Pro Karting Series')], help_text='Choose "none" if this isa practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='rear_axle_type',
            field=models.CharField(help_text='The type of the rear axle', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Final', 'Final race'), ('Heat', 'Heat race'), ('Practice', 'General Practice'), ('Pre-final', 'Pre-final race'), ('Qualifying', 'Qualifying Practice')], default='Practice', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='sprocket_size',
            field=models.IntegerField(blank=True, help_text='See below for shifter kart sprocket sizes'),
        ),
        migrations.AlterField(
            model_name='session',
            name='temp',
            field=models.IntegerField(help_text='Please enter the temperature in Fahrenheit.', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='track_conditions',
            field=models.TextField(blank=True, help_text='(Optional) Please enter a brief description of thetrack conditions.', null=True),
        ),
    ]
