# Generated by Django 4.2.7 on 2024-01-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0023_session_session_general_notes_session_sprocket_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
        migrations.AddField(
            model_name='session',
            name='session_time',
            field=models.TimeField(auto_now=True, db_column='time'),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('Kosmic', 'Kosmic'), ('KartRepublic', 'Kart Republic'), ('Tony Kart', 'Tony Kart'), ('CompKart', 'CompKart'), ('SODI', 'SODI Kart'), ('Red Speed', 'Red Speed'), ('BirelArt', 'BirelArt')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('Stars', 'Stars'), ('RokCup', 'ROK Cup'), ('Italian Championship', 'Italian Championship'), ('None', 'None'), ('Rotax', 'Rotax Races'), ('NEKC', 'Northeast Karting Championship'), ('SKUSA', 'Super Karts USA'), ('WSK', 'World Series Karting'), ('USPKS', 'US Pro Karting Series')], help_text='Choose "none" if this isa practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Pre-final', 'Pre-final race'), ('Qualifying', 'Qualifying Practice'), ('Heat', 'Heat race'), ('Final', 'Final race'), ('Practice', 'General Practice')], default='Practice', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='track_conditions',
            field=models.TextField(blank=True, help_text='(Optional) Please enter a brief description of the track conditions.', null=True),
        ),
    ]
