# Generated by Django 4.2.7 on 2024-01-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0024_remove_session_time_session_session_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('SODI', 'SODI Kart'), ('Red Speed', 'Red Speed'), ('CompKart', 'CompKart'), ('Tony Kart', 'Tony Kart'), ('KartRepublic', 'Kart Republic'), ('BirelArt', 'BirelArt'), ('Kosmic', 'Kosmic')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('SKUSA', 'Super Karts USA'), ('USPKS', 'US Pro Karting Series'), ('NEKC', 'Northeast Karting Championship'), ('WSK', 'World Series Karting'), ('RokCup', 'ROK Cup'), ('Rotax', 'Rotax Races'), ('None', 'None'), ('Italian Championship', 'Italian Championship'), ('Stars', 'Stars')], help_text='Choose "none" if this isa practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Heat', 'Heat race'), ('Qualifying', 'Qualifying Practice'), ('Pre-final', 'Pre-final race'), ('Practice', 'General Practice'), ('Final', 'Final race')], default='Practice', max_length=20),
        ),
    ]
