# Generated by Django 4.2.7 on 2024-01-20 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0025_alter_chassis_brand_alter_session_race_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('Kosmic', 'Kosmic'), ('SODI', 'SODI Kart'), ('CompKart', 'CompKart'), ('Tony Kart', 'Tony Kart'), ('BirelArt', 'BirelArt'), ('Red Speed', 'Red Speed'), ('KartRepublic', 'Kart Republic')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('Stars', 'Stars'), ('NEKC', 'Northeast Karting Championship'), ('RokCup', 'ROK Cup'), ('USPKS', 'US Pro Karting Series'), ('Rotax', 'Rotax Races'), ('None', 'None'), ('WSK', 'World Series Karting'), ('Italian Championship', 'Italian Championship'), ('SKUSA', 'Super Karts USA')], help_text='Choose "none" if this isa practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Practice', 'General Practice'), ('Final', 'Final race'), ('Pre-final', 'Pre-final race'), ('Qualifying', 'Qualifying Practice'), ('Heat', 'Heat race')], default='Practice', max_length=20),
        ),
    ]
