# Generated by Django 4.2.7 on 2024-01-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0026_engine_user_alter_chassis_brand_alter_session_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('Tony Kart', 'Tony Kart'), ('SODI', 'SODI Kart'), ('Red Speed', 'Red Speed'), ('KartRepublic', 'Kart Republic'), ('Kosmic', 'Kosmic'), ('CompKart', 'CompKart'), ('BirelArt', 'BirelArt')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('Rotax', 'Rotax Races'), ('Stars', 'Stars'), ('NEKC', 'Northeast Karting Championship'), ('Italian Championship', 'Italian Championship'), ('None', 'None'), ('SKUSA', 'Super Karts USA'), ('WSK', 'World Series Karting'), ('RokCup', 'ROK Cup'), ('USPKS', 'US Pro Karting Series')], help_text='Choose "none" if this isa practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Practice', 'General Practice'), ('Heat', 'Heat race'), ('Final', 'Final race'), ('Qualifying', 'Qualifying Practice'), ('Pre-final', 'Pre-final race')], default='Practice', max_length=20),
        ),
    ]
