# Generated by Django 4.2.7 on 2024-01-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0027_alter_chassis_brand_alter_session_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('BirelArt', 'BirelArt'), ('Red Speed', 'Red Speed'), ('CompKart', 'CompKart'), ('KartRepublic', 'Kart Republic'), ('Kosmic', 'Kosmic'), ('Tony Kart', 'Tony Kart'), ('SODI', 'SODI Kart')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('None', 'None'), ('WSK', 'World Series Karting'), ('Italian Championship', 'Italian Championship'), ('NEKC', 'Northeast Karting Championship'), ('RokCup', 'ROK Cup'), ('Rotax', 'Rotax Races'), ('USPKS', 'US Pro Karting Series'), ('SKUSA', 'Super Karts USA'), ('Stars', 'Stars')], help_text='Choose "none" if this isa practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Heat', 'Heat race'), ('Practice', 'General Practice'), ('Pre-final', 'Pre-final race'), ('Final', 'Final race'), ('Qualifying', 'Qualifying Practice')], default='Practice', max_length=20),
        ),
    ]
