# Generated by Django 4.2.7 on 2024-01-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0028_alter_chassis_brand_alter_session_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('Kosmic', 'Kosmic'), ('SODI', 'SODI Kart'), ('KartRepublic', 'Kart Republic'), ('Tony Kart', 'Tony Kart'), ('BirelArt', 'BirelArt'), ('CompKart', 'CompKart'), ('Red Speed', 'Red Speed')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('Rotax', 'Rotax Races'), ('WSK', 'World Series Karting'), ('NEKC', 'Northeast Karting Championship'), ('Stars', 'Stars'), ('USPKS', 'US Pro Karting Series'), ('SKUSA', 'Super Karts USA'), ('RokCup', 'ROK Cup'), ('None', 'None'), ('Italian Championship', 'Italian Championship')], help_text='Choose "none" if this isa practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Pre-final', 'Pre-final race'), ('Practice', 'General Practice'), ('Final', 'Final race'), ('Qualifying', 'Qualifying Practice'), ('Heat', 'Heat race')], default='Practice', max_length=20),
        ),
    ]
