# Generated by Django 4.2.7 on 2024-01-21 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0029_alter_chassis_brand_alter_session_race_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('Tony Kart', 'Tony Kart'), ('KartRepublic', 'Kart Republic'), ('BirelArt', 'BirelArt'), ('Red Speed', 'Red Speed'), ('SODI', 'SODI Kart'), ('Kosmic', 'Kosmic'), ('CompKart', 'CompKart')], max_length=200),
        ),
        migrations.AlterField(
            model_name='engine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('NEKC', 'Northeast Karting Championship'), ('USPKS', 'US Pro Karting Series'), ('WSK', 'World Series Karting'), ('None', 'None'), ('SKUSA', 'Super Karts USA'), ('Rotax', 'Rotax Races'), ('RokCup', 'ROK Cup'), ('Stars', 'Stars'), ('Italian Championship', 'Italian Championship')], help_text='Choose "none" if this isa practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Heat', 'Heat race'), ('Final', 'Final race'), ('Pre-final', 'Pre-final race'), ('Practice', 'General Practice'), ('Qualifying', 'Qualifying Practice')], default='Practice', max_length=20),
        ),
    ]
