# Generated by Django 4.2.7 on 2024-01-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0030_chassis_user_session_time_session_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('KartRepublic', 'Kart Republic'), ('Red Speed', 'Red Speed'), ('Tony Kart', 'Tony Kart'), ('Kosmic', 'Kosmic'), ('CompKart', 'CompKart'), ('BirelArt', 'BirelArt'), ('SODI', 'SODI Kart')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('SKUSA', 'Super Karts USA'), ('Italian Championship', 'Italian Championship'), ('None', 'None'), ('Rotax', 'Rotax Races'), ('NEKC', 'Northeast Karting Championship'), ('RokCup', 'ROK Cup'), ('WSK', 'World Series Karting'), ('Stars', 'Stars'), ('USPKS', 'US Pro Karting Series')], help_text='Choose "none" if this isa practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Qualifying', 'Qualifying Practice'), ('Heat', 'Heat race'), ('Practice', 'General Practice'), ('Pre-final', 'Pre-final race'), ('Final', 'Final race')], default='Practice', max_length=20),
        ),
    ]
