# Generated by Django 4.2.7 on 2024-01-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0031_alter_chassis_brand_alter_session_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('Red Speed', 'Red Speed'), ('KartRepublic', 'Kart Republic'), ('SODI', 'SODI Kart'), ('CompKart', 'CompKart'), ('Tony Kart', 'Tony Kart'), ('Kosmic', 'Kosmic'), ('BirelArt', 'BirelArt')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('Rotax', 'Rotax Races'), ('WSK', 'World Series Karting'), ('Stars', 'Stars'), ('SKUSA', 'Super Karts USA'), ('USPKS', 'US Pro Karting Series'), ('RokCup', 'ROK Cup'), ('Italian Championship', 'Italian Championship'), ('None', 'None'), ('NEKC', 'Northeast Karting Championship')], help_text='Choose "none" if this isa practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Final', 'Final race'), ('Qualifying', 'Qualifying Practice'), ('Practice', 'General Practice'), ('Heat', 'Heat race'), ('Pre-final', 'Pre-final race')], default='Practice', max_length=20),
        ),
    ]
