# Generated by Django 4.2.7 on 2024-01-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0033_alter_chassis_brand_alter_session_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('KartRepublic', 'Kart Republic'), ('CompKart', 'CompKart'), ('Kosmic', 'Kosmic'), ('BirelArt', 'BirelArt'), ('SODI', 'SODI Kart'), ('Red Speed', 'Red Speed'), ('Tony Kart', 'Tony Kart')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('USPKS', 'US Pro Karting Series'), ('WSK', 'World Series Karting'), ('NEKC', 'Northeast Karting Championship'), ('RokCup', 'ROK Cup'), ('Italian Championship', 'Italian Championship'), ('SKUSA', 'Super Karts USA'), ('Stars', 'Stars'), ('None', 'None'), ('Rotax', 'Rotax Races')], help_text='Choose "none" if this isa practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Pre-final', 'Pre-final race'), ('Qualifying', 'Qualifying Practice'), ('Practice', 'General Practice'), ('Heat', 'Heat race'), ('Final', 'Final race')], default='Practice', max_length=20),
        ),
    ]
