# Generated by Django 4.2.7 on 2024-01-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0034_alter_chassis_brand_alter_session_race_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('KartRepublic', 'Kart Republic'), ('Kosmic', 'Kosmic'), ('CompKart', 'CompKart'), ('Tony Kart', 'Tony Kart'), ('BirelArt', 'BirelArt'), ('SODI', 'SODI Kart'), ('Red Speed', 'Red Speed')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('Rotax', 'Rotax Races'), ('Italian Championship', 'Italian Championship'), ('RokCup', 'ROK Cup'), ('Stars', 'Stars'), ('NEKC', 'Northeast Karting Championship'), ('None', 'None'), ('SKUSA', 'Super Karts USA'), ('WSK', 'World Series Karting'), ('USPKS', 'US Pro Karting Series')], help_text='Choose "none" if this isa practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Pre-final', 'Pre-final race'), ('Final', 'Final race'), ('Practice', 'General Practice'), ('Qualifying', 'Qualifying Practice'), ('Heat', 'Heat race')], default='Practice', max_length=20),
        ),
    ]
