# Generated by Django 4.2.7 on 2024-03-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0037_alter_chassis_brand_alter_session_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='brand',
            field=models.CharField(choices=[('SODI', 'SODI Kart'), ('Tony Kart', 'Tony Kart'), ('CompKart', 'CompKart'), ('Red Speed', 'Red Speed'), ('KartRepublic', 'Kart Republic'), ('BirelArt', 'BirelArt'), ('Kosmic', 'Kosmic')], max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('WSK', 'World Series Karting'), ('Rotax', 'Rotax Races'), ('NEKC', 'Northeast Karting Championship'), ('USPKS', 'US Pro Karting Series'), ('Italian Championship', 'Italian Championship'), ('RokCup', 'ROK Cup'), ('None', 'None'), ('Stars', 'Stars'), ('SKUSA', 'Super Karts USA')], help_text='Choose "none" if this is a practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Practice', 'General Practice'), ('Pre-final', 'Pre-final race'), ('Heat', 'Heat race'), ('Final', 'Final race'), ('Qualifying', 'Qualifying Practice')], default='Practice', max_length=20),
        ),
    ]
