# Generated by Django 4.2.7 on 2024-04-01 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0039_track_alter_chassis_brand_alter_session_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('USPKS', 'US Pro Karting Series'), ('SKUSA', 'Super Karts USA'), ('Rotax', 'Rotax Races'), ('RokCup', 'ROK Cup'), ('None', 'None'), ('Stars', 'Stars'), ('WSK', 'World Series Karting'), ('NEKC', 'Northeast Karting Championship'), ('Italian Championship', 'Italian Championship')], help_text='Choose "none" if this is a practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Pre-final', 'Pre-final race'), ('Final', 'Final race'), ('Qualifying', 'Qualifying Practice'), ('Heat', 'Heat race'), ('Practice', 'General Practice')], default='Practice', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='session.track'),
        ),
    ]
