# Generated by Django 4.2.7 on 2024-04-13 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0040_alter_session_race_alter_session_session_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='race',
            field=models.CharField(choices=[('WSK', 'World Series Karting'), ('NEKC', 'Northeast Karting Championship'), ('Italian Championship', 'Italian Championship'), ('USPKS', 'US Pro Karting Series'), ('SKUSA', 'Super Karts USA'), ('None', 'None'), ('Rotax', 'Rotax Races'), ('Stars', 'Stars'), ('RokCup', 'ROK Cup')], help_text='Choose "none" if this is a practice weekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Heat', 'Heat race'), ('Practice', 'General Practice'), ('Pre-final', 'Pre-final race'), ('Qualifying', 'Qualifying Practice'), ('Final', 'Final race')], default='Practice', max_length=20),
        ),
    ]
