# Generated by Django 4.2.7 on 2024-07-13 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("session", "0041_track_created_by_alter_session_race_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="driver_name",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="race",
            field=models.CharField(
                choices=[
                    ("Stars", "Stars"),
                    ("WSK", "World Series Karting"),
                    ("RokCup", "ROK Cup"),
                    ("USPKS", "US Pro Karting Series"),
                    ("None", "None"),
                    ("SKUSA", "Super Karts USA"),
                    ("Italian Championship", "Italian Championship"),
                    ("NEKC", "Northeast Karting Championship"),
                    ("Rotax", "Rotax Races"),
                ],
                help_text='Choose "none" if this is a practice weekend',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("Qualifying", "Qualifying Practice"),
                    ("Final", "Final race"),
                    ("Pre-final", "Pre-final race"),
                    ("Heat", "Heat race"),
                    ("Practice", "General Practice"),
                ],
                default="Practice",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="tire_type",
            field=models.CharField(
                blank=True,
                default="sleek",
                help_text="Wets or sleek?",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="track",
            field=models.ForeignKey(
                help_text="You can see the tracks you added together with those added by the administrator",
                on_delete=django.db.models.deletion.PROTECT,
                to="session.track",
            ),
        ),
    ]
